version: '3'

networks:
  spp-laravel:

volumes:
  spp-paud-vol: {}

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks: 
      - spp-laravel

  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - spp-paud-vol:/var/lib/mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - "4406:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: sppdbpassword
      MYSQL_DATABASE: spppaud
      MYSQL_USER: spppaud_user
      MYSQL_PASSWORD: secretpass
    networks:
      - spp-laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes: 
      - ../:/var/www
    # depends_on:
    #   - mysql
    # working_dir: /var/www
    # command: "./start.sh"
    ports:
      - "9000:9000"
    networks:
      - spp-laravel